Display info in tables according to data from
neo4j-examples/paradise-papers-django pull request #23
Opened 2018-01-13 15:41 UTC by mariamera

API

Closes [Ticket](https://trello.com)

## Testing

Steps to manually verify the change:
1. _Setup_: open `paradise-papers-django/search_frontend/index.html`
2. _Exercise_: click search. 
3. _Verify_: check if information through tabs are dynamically. 
PS: only the information, not the header text 👍 
ex : 
![image](https://user-images.githubusercontent.com/29434543/34907535-8f267d76-f856-11e7-9310-c8377a266be3.png)

![image](https://user-images.githubusercontent.com/29434543/34907536-9800a34a-f856-11e7-8a0c-ae9bb9ea6777.png)

![image](https://user-images.githubusercontent.com/29434543/34907537-a2816c00-f856-11e7-8953-b1ee6f9af8b7.png)

2018-01-13 18:16 UTC, jrbaez01 commented on search_frontend/js/search.js
> +      var list = []
Always use `let`.

2018-01-13 18:23 UTC, jrbaez01 commented on search_frontend/js/search.js
> +          if (key == this._node_type ) {
Unnecessary loop, you could have done this:
```
if (mockup_data.filterData.hasOwnProperty(this._node_type)) {
  // Do stuff with  mockup_data.filterData[this._node_type]
}
```

2018-01-13 18:32 UTC, jrbaez01 commented on search_frontend/js/search.js
> +    findStructure() {
It seems what is being done here only need to be done once. The constructor is a good place this.

2018-01-13 18:35 UTC, jrbaez01 commented on search_frontend/js/search.js
> +          this.findStructure(mockup_data.filterData);
Each time we call fetch, findStructure is executed. This should be done in the constructor.

2018-01-13 18:35 UTC, oscarpolanco commented on search_frontend/index.html
> +                    <td data-bind="text: $data" ></td>
Extra space here

2018-01-13 18:46 UTC, junior1q94 requested changes
Great work making the table rows dynamic! We just need to refactor now. @mariamera

2018-01-13 22:00 UTC, oscarpolanco commented on search_frontend/index.html
> +                    <td data-bind="text: $parent[$data.property_name]" >sd</td>
Extra space here

2018-01-13 22:06 UTC, oscarpolanco approved these changes
LGTM

2018-01-14 00:24 UTC, junior1q94 approved these changes

2018-01-14 00:25 UTC, merged