feature/19: create filter by Data Source
neo4j-examples/paradise-papers-django pull request #43
Opened 2018-01-22 18:37 UTC by mariamera

Closes [Ticket](https://trello.com/c/eGqFgh9e/19-as-a-user-i-want-a-feature-to-filter-results-of-the-search-so-that-i-can-see-specific-results-by-category)

## Testing

Steps to manually verify the change:
1. _Setup_: Runenvironment
2. _Exercise_: on the home page look at the filters.
3. _Verify_: Check if `filter by Data Source` is there. and check when you look at the filter it display the correct information

2018-01-22 18:59 UTC, junior1q94 requested changes

2018-01-22 18:59 UTC, jrbaez01 commented on paradise_papers_search/fetch_api/models/helpers.py
> +    data_source            = count_info['sourceID']
Align line with others. Just because it looks nice...

2018-01-22 18:59 UTC, jrbaez01 commented on paradise_papers_search/paradise_papers_search/constants.py
> +	RETURN DISTINCT n.sourceID AS dataSOurce
Alias name "dataSOurce" looks weird... 
Add new line at the end.

2018-01-22 19:06 UTC, junior1q94 approved these changes

2018-01-23 14:52 UTC, oscarpolanco reviewed
Minors comments after that LGTM

2018-01-23 14:52 UTC, oscarpolanco commented on paradise_papers_search/paradise_papers_search/constants.py
> +DATASOURCE = sorted([data_source[0] for data_source in data_sources if isinstance(data_source[0], str)] )
Extra space before the last parenthesis

2018-01-23 14:52 UTC, oscarpolanco commented on paradise_papers_search/templates/index.html
> +                  <span class="input-group-text" id="">By Data Source:</span>
Do we need the id here?

2018-01-23 15:41 UTC, mariamera commented on paradise_papers_search/templates/index.html
> +                  <span class="input-group-text" id="">By Data Source:</span>
No, I will take it out

2018-01-23 18:23 UTC, oscarpolanco approved these changes
LGTM after squash
Good job!!

2018-01-23 18:26 UTC, merged