doc: How to create the API
neo4j-examples/paradise-papers-django pull request #53
Opened 2018-01-26 20:39 UTC by raulgomezc

Closes [Ticket](https://trello.com)

## Testing

Steps to manually verify the change:
1. _Setup_: step to set the environment
2. _Exercise_: How to run the environment and example link: [Test Link](http://127.0.0.1:8000/)
3. _Verify_: what we need to verify

2018-01-26 21:07 UTC, mariamera commented on docs/tutorial/part05.rst
> +We decided to use APIs to fetch the data to make queries more effective, as sometimes queries get too big, we decided it was better to fetch the data in little chunks rather than one big request and
maybe a dot instead of comma in `get too big, we decided it was better to`

2018-01-26 21:07 UTC, mariamera commented on docs/tutorial/part05.rst
> +In this project, we are using the rest_framework_ library because it has some simple non-limiting ways to implement an API structure, if you desire you can use any of your choosing, but the examples
same here in ` implement an API structure, if you desire `

2018-01-30 12:01 UTC, mariamera commented on docs/tutorial/part05.rst
> +``curl http://127.0.0.1:8000/fetch/nodes``
Nice example 👍 💛

2018-01-30 15:49 UTC, oscarpolanco commented on docs/tutorial/part05.rst
> +The other 5 endpoints with its classes/URLs respectively are :
Extra space before the dots

2018-01-30 15:49 UTC, oscarpolanco commented on docs/tutorial/part05.rst
> +    pip install rest_framework
This is already in the requirement file; maybe the user already has this if he is following the tutorial. Maybe a note pointing this should be useful?
What do you think? 🤔

2018-02-01 20:11 UTC, oscarpolanco approved these changes
LGTM

2018-02-05 16:52 UTC, cyuli commented on docs/tutorial/part05.rst
> +    pip install rest_framework
No matching distribuition found for rest_framework. Maybe it refers to djangorestframework library. No?

2018-02-05 16:52 UTC, cyuli commented on docs/tutorial/part05.rst
> +Now on your ``fetch_api/urls.py`` add the endpoint to the urls::
It doesn't exists, i think that would be good to say that they should to create it.

2018-02-08 13:49 UTC, EnmanuelParache commented on docs/tutorial/part05.rst
> +Why the API structure
Question (?) mark?

2018-02-08 13:49 UTC, EnmanuelParache commented on docs/tutorial/part05.rst
> +Explain the library
'Explain the library' sounds weird (boring to be honest). Instead use something like 'REST API' or 'Implementing REST framework for API' it's more attractive and useful for somebody that is only looking for this.

2018-02-08 13:49 UTC, EnmanuelParache commented on docs/tutorial/part05.rst
> +Now you can hit the endpoint with a method of your choosing, for this example, we are going to use
method of your preference

2018-02-13 20:26 UTC, mariamera commented on docs/tutorial/part05.rst
> +focus on one to explain the process of making them, we are going to be building the
I think it is better a dot instead of a comma after 'them' and before 'we'

2018-02-13 20:27 UTC, mariamera commented on docs/tutorial/part05.rst
> +Now create this file ``fetch_api/urls.py`` and fill it with this::
the file ``fetch_api/urls.py`` is created in part 3.

 You can see it here: https://github.com/neo4j-examples/paradise-papers-django/pull/51/files#diff-c1e0a5d898826045a3e281cad742e750R25

2018-02-14 14:09 UTC, mariamera commented
The file `nodeutils.py` is never created on the tutorial , I think we should add this here.

2018-02-14 14:09 UTC, mariamera requested changes
.

2018-02-14 19:34 UTC, merged