Add the navigation bar with the topics
neo4j-examples/paradise-papers-django pull request #56
Opened 2018-02-07 18:41 UTC by mariamera

Closes [Ticket](https://trello.com)

2018-02-08 15:21 UTC, jrbaez01 commented
LGTM
FYI: @raulgomezc  @oscarpolanco

2018-02-08 15:21 UTC, junior1q94 approved these changes

2018-02-08 15:26 UTC, EnmanuelParache commented
I think the content section should scroll along with the page so that I don't have to scroll back up to change to a section.

2018-02-08 18:56 UTC, oscarpolanco approved these changes
LGTM

2018-02-12 14:30 UTC, raulgomezc requested changes

2018-02-12 14:30 UTC, raulgomezc commented on docs/conf.py
> +
Remove surplus line

2018-02-12 14:32 UTC, raulgomezc approved these changes
LGTM

2018-02-12 14:32 UTC, merged